language: python
python:
  - '3.9.12'

# safelist
branches:
  only:
    - staging

before_script:
  - sudo systemctl start postgresql@13-main
  - pg_lsclusters
  - python manage.py runserver &
  - chmod +x ./coverage.sh

addons:
  addons:
  postgresql: "13"
  apt:
    packages:
    - postgresql-13
    - postgresql-client-13

services:
  - postgresql

env: 
  global:
    - PGPORT=5432
    - DJANGO_SETTINGS_MODULE=config.settings.travis
    - DJANGO_KEY=django-insecure-be12llf1uqajc#jnp5$1@lyaf=$-8yyavk!twj%f9u4#+a^6-
    - DB_USER=travis
    - DB_PWD=
    - DB_NAME=
    - DB_TEST=

script:
  - ./coverage.sh