language: python
python:
  - '3.9.12'

# safelist
branches:
  only:
    - staging

before_script:
  - chmod +x ./coverage.sh
  - python manage.py runserver &

addons:
  postgresql: "14.3"
  apt:
        packages:
        - postgresql-14
        - postgresql-client-14

services:
  - postgresql

env: 
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.travis
    - DJANGO_KEY=django-insecure-be12llf1uqajc#jnp5$1@lyaf=$-8yyavk!twj%f9u4#+a^6-
    - DB_USER=postgres
    - DB_PWD=
    - DB_NAME=
    - DB_TEST=

script:
  - ./coverage.sh