language: python
python:
  - '3.9.12'

# safelist
branches:
  only:
    - staging

before_script:
  - chmod +x ./coverage.sh
  - python manage.py runserver &

addons:
  addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

services:
  - postgresql

env: 
  global:
    - PGPORT=5433
    - DJANGO_SETTINGS_MODULE=config.settings.travis
    - DJANGO_KEY=django-insecure-be12llf1uqajc#jnp5$1@lyaf=$-8yyavk!twj%f9u4#+a^6-
    - DB_USER=travis
    - DB_PWD=
    - DB_NAME=
    - DB_TEST=

script:
  - ./coverage.sh